### ISSUE TITLE
Please change the description

### ISSUE THREAD

**Issue by hroncok** [ctu-yfsg/2015-f-citygml#2]
I'd like to have all in this repository in English. Could you plese change the description of this repository to:

    Python library converting CityGML to printable STL

Thanks.

**Comment by jirutka** [comment]
+1

**Comment by landam** [comment]
OK, closing.

**Comment by hroncok** [comment]
Well, I still see Skupina F (akademický rok 2014/2015)

**Comment by landam** [comment]
fixed

**Comment by hroncok** [comment]
Could it please be

    Python library converting CityGML to printable STL

as stated in the issue description?

**Comment by hroncok** [comment]
bump?

**Comment by landam** [comment]
done

**Comment by hroncok** [comment]
Thank You
