### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by hroncok** [ctu-yfsg/2015-f-citygml#3]
In the near future, I'd like to use [Travis CI](https://travis-ci.org/) for this repository, however, I have no ACL to enable it.

Could you plese log in to Travis CI with your GitHub account, got o [ctu-yfsg settings](https://travis-ci.org/profile/ctu-yfsg), and enable this repo. Then plese go to the repository settings (cog symbol next to the enable switch) and check **Build only if .travis.yml is present**.

Thanks

**Comment by landam** [comment]
Should be done

**Comment by hroncok** [comment]
Thanks, it works
